export const GENRES = [
  "Lo-Fi",
  "Hip Hop",
  "Pop",
  "Rock",
  "Electronic",
  "Jazz",
  "Classical",
  "R&B",
  "Ambient",
  "Cinematic",
  "Funk",
  "Reggae",
  "Country",
  "Folk",
  "Metal",
  "Indie",
  "EDM",
  "Trap",
  "Chillwave",
  "Synthwave",
] as const;

export const MOODS = [
  "Chill",
  "Energetic",
  "Happy",
  "Sad",
  "Dark",
  "Uplifting",
  "Mysterious",
  "Romantic",
  "Aggressive",
  "Peaceful",
  "Dreamy",
  "Intense",
  "Playful",
  "Epic",
  "Nostalgic",
  "Warm",
] as const;

export const ERAS = [
  "1960s",
  "1970s",
  "1980s Retro",
  "1990s",
  "2000s",
  "2010s",
  "Modern / Current",
  "Futuristic",
  "Timeless",
] as const;

export const TEMPOS = [
  "Very Slow",
  "Slow",
  "Medium",
  "Upbeat",
  "Fast",
  "Very Fast",
] as const;

export const INSTRUMENTS = [
  "Acoustic Guitar",
  "Electric Guitar",
  "Bass Guitar",
  "Piano",
  "Synthesizer",
  "Drums",
  "Violin",
  "Cello",
  "Trumpet",
  "Saxophone",
  "Flute",
  "Ukulele",
  "Harp",
  "Organ",
  "Marimba",
  "Steel Drums",
  "Banjo",
  "Harmonica",
  "808 Bass",
  "Pad Synth",
] as const;

export const DURATION_OPTIONS = [
  { label: "5 seconds", value: 5 },
  { label: "10 seconds", value: 10 },
  { label: "15 seconds", value: 15 },
  { label: "30 seconds", value: 30 },
] as const;

export const CONTENT_TYPES = [
  "Gaming",
  "Vlogging",
  "Cooking",
  "Travel",
  "Tech Reviews",
  "Beauty / Fashion",
  "Fitness",
  "Education",
  "Comedy",
  "Music",
  "Art / Creative",
  "News / Commentary",
  "Outdoors / Nature",
  "DIY / Crafts",
  "ASMR",
  "Podcast",
] as const;